'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'

const DEMO_FILES: Record<string, { lang: string; lines: React.ReactNode[] }> = {
  'App.jsx': {
    lang: 'jsx',
    lines: [
      <><span className="token-kw">import</span> React <span className="token-kw">from</span> <span className="token-str">&apos;react&apos;</span></>,
      <><span className="token-kw">import</span> {'{ Navigation, Hero, Features, Footer }'} <span className="token-kw">from</span> <span className="token-str">&apos;./components&apos;</span></>,
      <span className="token-cmt">// Generated by ui2code · Next.js + Tailwind</span>,
      <></>,
      <><span className="token-kw">export default function</span> <span className="token-fn">GeneratedApp</span><span className="text-slate-400">()</span> {'{'}</>,
      <>&nbsp;&nbsp;<span className="token-kw">return</span> {'('}</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;main</span> <span className="token-attr">className</span>=<span className="token-str">&quot;min-h-screen bg-white&quot;</span><span className="token-tag">&gt;</span></>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;Navigation</span> <span className="token-attr">sticky</span> <span className="token-tag">/&gt;</span></>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;Hero</span> <span className="token-attr">headline</span>=<span className="token-str">&quot;Welcome&quot;</span> <span className="token-tag">/&gt;</span></>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;Features</span> <span className="token-attr">items</span>=&#123;<span className="text-orange-400">data.features</span>&#125; <span className="token-tag">/&gt;</span></>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;Footer</span> <span className="token-attr">links</span>=&#123;<span className="text-orange-400">data.footer</span>&#125; <span className="token-tag">/&gt;</span></>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-tag">&lt;/main&gt;</span></>,
      <>&nbsp;&nbsp;<span className="text-slate-400">)</span></>,
      <span className="text-slate-400">{'}'}</span>,
    ],
  },
  'tailwind.config.js': {
    lang: 'js',
    lines: [
      <><span className="token-cmt">// Generated Tailwind config from design system</span></>,
      <><span className="token-fn">module</span>.<span className="token-fn">exports</span> = {'{'}</>,
      <>&nbsp;&nbsp;<span className="token-attr">content</span>: [<span className="token-str">&apos;./src/**/*.&#123;js,jsx,ts,tsx&#125;&apos;</span>],</>,
      <>&nbsp;&nbsp;<span className="token-attr">theme</span>: {'{'}</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-attr">extend</span>: {'{'}</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-attr">colors</span>: {'{'}</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-str">primary</span>: <span className="token-str">&apos;#246bfe&apos;</span>,</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-str">secondary</span>: <span className="token-str">&apos;#8b5cf6&apos;</span>,</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span className="token-str">accent</span>: <span className="token-str">&apos;#06b6d4&apos;</span>,</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{'}'}</>,
      <>&nbsp;&nbsp;&nbsp;&nbsp;{'}'}</>,
      <>&nbsp;&nbsp;{'}'}</>,
      <span className="text-slate-400">{'}'}</span>,
    ],
  },
  'style.css': {
    lang: 'css',
    lines: [
      <><span className="token-cmt">/* Generated design tokens */</span></>,
      <><span className="token-tag">:root</span> {'{'}</>,
      <>&nbsp;&nbsp;<span className="token-attr">--color-primary</span>: <span className="token-str">#246bfe</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">--color-secondary</span>: <span className="token-str">#8b5cf6</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">--font-family</span>: <span className="token-str">Inter, system-ui</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">--spacing-md</span>: <span className="token-num">16px</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">--radius-md</span>: <span className="token-num">8px</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">--shadow-md</span>: <span className="token-str">0 4px 6px rgba(0,0,0,.1)</span>;</>,
      <span className="text-slate-400">{'}'}</span>,
      <></>,
      <><span className="token-tag">.hero</span> {'{'}</>,
      <>&nbsp;&nbsp;<span className="token-attr">display</span>: <span className="token-str">flex</span>;</>,
      <>&nbsp;&nbsp;<span className="token-attr">padding</span>: <span className="token-num">5rem 2rem</span>;</>,
      <span className="text-slate-400">{'}'}</span>,
    ],
  },
}

export default function DemoSection() {
  const [activeFile, setActiveFile] = useState('App.jsx')
  const file = DEMO_FILES[activeFile]

  return (
    <section id="demo" className="py-28 px-6 relative overflow-hidden">
      <div className="absolute top-1/2 left-0 w-96 h-96 bg-indigo-600/10 rounded-full blur-[120px] pointer-events-none -translate-y-1/2" aria-hidden="true" />

      <div className="relative z-10 max-w-6xl mx-auto">
        <div className="grid lg:grid-cols-2 gap-14 items-center">
          {/* Left: copy */}
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7 }}
          >
            <span className="inline-flex items-center gap-2 px-3 py-1.5 mb-5 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 text-xs font-semibold tracking-wide uppercase">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
              Live output preview
            </span>
            <h2 className="text-4xl lg:text-5xl font-black text-white tracking-[-0.03em] mb-5">
              Clean screenshot.<br />
              <span className="gradient-text">Production-ready code.</span>
            </h2>
            <p className="text-slate-400 text-lg leading-relaxed mb-6">
              The studio shows your extracted component hierarchy, design tokens, layout intelligence, and all generated files — side by side with your screenshot.
            </p>
            <ul className="space-y-3 mb-8">
              {[
                'Component hierarchy tree',
                'Extracted design system tokens',
                'Layout intelligence JSON',
                'Framework-specific code files',
                'One-click ZIP download',
              ].map((item) => (
                <li key={item} className="flex items-center gap-3 text-slate-300 text-sm">
                  <span className="w-5 h-5 rounded-full bg-indigo-500/20 border border-indigo-500/40 flex items-center justify-center flex-shrink-0">
                    <svg width="10" height="10" viewBox="0 0 10 10" fill="none" aria-hidden="true">
                      <path d="M2 5l2.5 2.5L8 3" stroke="#818cf8" strokeWidth="1.5" strokeLinecap="round" />
                    </svg>
                  </span>
                  {item}
                </li>
              ))}
            </ul>
            <a
              href="#studio"
              className="inline-flex items-center gap-2 px-6 py-3.5 font-semibold text-white rounded-xl bg-indigo-600 hover:bg-indigo-500 transition-all duration-200 shadow-[0_0_24px_rgba(99,102,241,0.4)]"
            >
              Start generating →
            </a>
          </motion.div>

          {/* Right: code editor mockup */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, delay: 0.1 }}
          >
            <div className="rounded-2xl overflow-hidden shadow-2xl border border-white/[0.08]">
              {/* Window bar */}
              <div className="flex items-center gap-2 px-4 py-3 bg-[#0d1117] border-b border-white/[0.06]">
                <span className="w-3 h-3 rounded-full bg-red-500/70" />
                <span className="w-3 h-3 rounded-full bg-yellow-500/70" />
                <span className="w-3 h-3 rounded-full bg-green-500/70" />
                <div className="flex-1" />
                <span className="text-xs text-slate-600 font-mono">ui2code studio</span>
              </div>

              {/* Split: screenshot + code */}
              <div className="grid grid-cols-[1fr_1.4fr]">
                {/* Mock screenshot */}
                <div className="bg-[#0a0a0a] border-r border-white/[0.06] p-3">
                  <div className="h-3 bg-white/[0.06] rounded-sm mb-2 w-4/5" />
                  <div className="h-12 bg-gradient-to-br from-indigo-500/20 to-violet-500/20 rounded-lg mb-2" />
                  <div className="grid grid-cols-3 gap-1.5 mb-2">
                    {[1,2,3].map(i=><div key={i} className="h-8 bg-white/[0.04] rounded" />)}
                  </div>
                  <div className="space-y-1.5">
                    <div className="h-1.5 bg-white/[0.05] rounded-full w-full" />
                    <div className="h-1.5 bg-white/[0.05] rounded-full w-3/4" />
                    <div className="h-1.5 bg-white/[0.05] rounded-full w-1/2" />
                  </div>
                </div>

                {/* Code panel */}
                <div className="bg-[#0d1117]">
                  {/* Tabs */}
                  <div className="flex border-b border-white/[0.06] overflow-x-auto">
                    {Object.keys(DEMO_FILES).map((name) => (
                      <button
                        key={name}
                        onClick={() => setActiveFile(name)}
                        className={`px-3 py-2 text-[11px] font-mono whitespace-nowrap transition-colors border-b-2 ${
                          activeFile === name
                            ? 'text-indigo-300 border-indigo-500 bg-indigo-500/10'
                            : 'text-slate-500 border-transparent hover:text-slate-300'
                        }`}
                      >
                        {name}
                      </button>
                    ))}
                  </div>

                  {/* Lines */}
                  <div className="p-3 font-mono text-[11px] leading-6 overflow-hidden max-h-[280px]">
                    {file.lines.map((line, i) => (
                      <div key={i} className="flex">
                        <span className="w-6 text-slate-700 select-none text-right mr-3 flex-shrink-0">{i + 1}</span>
                        <span className="text-slate-300 whitespace-pre">{line}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
